color: null
fieldLayouts:
  b6944471-2fc5-4780-b628-abc7e1184d36:
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-04-15T10:21:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 016e9ada-2e97-441a-8e42-6a0e99dace91 # Duel - Rival One
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f59b2ebc-57c0-43f6-a251-c14a429df446
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-15T10:21:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 474c035f-d206-4c2e-9c47-47a068346e3f # Duel - Rival Two
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 543cb6e4-3dfe-4890-bd53-08327324055c
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-04-15T10:21:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 187d56a1-6b24-4822-9bff-edefcc4d69a9 # Duel - Score
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 00cc44ad-84b6-43aa-a0c3-6e5968101db1
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-15T10:21:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4a6ea415-82b1-4f1b-8ac0-d2d174361b8e
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 56aca303-2529-497b-996a-5f0e6db1ac88
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-04-15T10:21:07+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a82e81c-5b52-4065-9190-b54854ea0b06
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fa2a8f3b-e921-4479-90af-ad264b9435d1
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 55cbbf75-68f9-41bf-98b8-7ad1f5ddc242
        userCondition: null
handle: duel
hasTitleField: false
icon: alien
name: Duel
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ object.duelRivalOne.one().title } vs { object.duelRivalTwo.one().title }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
