columnSuffix: null
handle: duelScore
instructions: null
name: 'Duel - Score'
searchable: false
settings:
  decimals: 7
  defaultValue: null
  max: null
  min: 0
  prefix: null
  previewCurrency: null
  previewFormat: decimal
  size: null
  step: null
  suffix: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Number
