defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a1b9e011-ff18-423b-9b80-c99494031cb7 # Home
handle: home
maxAuthors: 1
name: Home
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6eab4b84-63fb-4382-bdd7-d2bee959aafb: # $SITE_NAME
    enabledByDefault: true
    hasUrls: true
    template: _entry/index.twig
    uriFormat: __home__
type: single
