defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: f6520888-6360-47ab-8daf-f7068c3ccef3 # Vote
handle: votes
maxAuthors: 1
name: Votes
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  6eab4b84-63fb-4382-bdd7-d2bee959aafb: # $SITE_NAME
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
